version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/zpi # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - run:
          command:|
              echo "COKOLWIEK" > /zpi/artifact-1;
              mkdir /zpi/artifacts;
              echo "COKOLWIEK" > /zpi/artifacts/artifact-2;
              
      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: zpi-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline # gets the project dependencies
      
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: zpi-{{ checksum "pom.xml" }}
      
      - run: mvn package # run the actual tests
      
      
      - store_artifacts:
          path: /zpi/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /zpi/artifacts