version: 2 # use CircleCI 2.0
jobs: 
  build: 
    
    working_directory: ~/testf 

    docker: 
      - image: circleci/openjdk:8-jdk-browsers 

    steps: 
      
      - checkout 
      
      - restore_cache: 
          key: testf-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline 
      
      - save_cache:
          paths:
            - ~/.m2
          key: testf-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
          
     
      - store_artifacts:
          path: target/z-0.0.1-SNAPSHOT.jar